# Generated by Django 5.2.3 on 2025-07-20 13:15

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("surveys", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestionAnalytics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("total_answers", models.IntegerField(default=0)),
                ("skip_count", models.IntegerField(default=0)),
                ("word_cloud_data", models.JSONField(default=dict)),
                ("sentiment_score", models.FloatField(blank=True, null=True)),
                ("choice_distribution", models.JSONField(default=dict)),
                ("average_value", models.FloatField(blank=True, null=True)),
                ("median_value", models.FloatField(blank=True, null=True)),
                ("min_value", models.FloatField(blank=True, null=True)),
                ("max_value", models.FloatField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "question",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="surveys.question",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="SurveyAnalytics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("total_views", models.IntegerField(default=0)),
                ("total_starts", models.IntegerField(default=0)),
                ("total_completions", models.IntegerField(default=0)),
                (
                    "average_completion_time",
                    models.DurationField(blank=True, null=True),
                ),
                ("median_completion_time", models.DurationField(blank=True, null=True)),
                ("bounce_rate", models.FloatField(default=0.0)),
                ("completion_rate", models.FloatField(default=0.0)),
                ("mobile_responses", models.IntegerField(default=0)),
                ("desktop_responses", models.IntegerField(default=0)),
                ("tablet_responses", models.IntegerField(default=0)),
                ("top_countries", models.JSONField(default=dict)),
                ("top_cities", models.JSONField(default=dict)),
                ("traffic_sources", models.JSONField(default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "survey",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="surveys.survey",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at", "-id"],
            },
        ),
    ]
