repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff (from Poetry)
        entry: poetry run ruff check
        language: system
        types: [python]
        args: ["--fix"]

      - id: ruff-format
        name: ruff format (from Poetry)
        entry: poetry run ruff format
        language: system
        types: [python]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: debug-statements
