# Generated by Django 5.2.3 on 2025-07-20 06:22

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("surveys", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("sms", "SMS"),
                            ("webhook", "Webhook"),
                            ("slack", "Slack"),
                        ],
                        help_text="Type of notification channel (e.g., Email, SMS, etc.)",
                        max_length=10,
                    ),
                ),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("INVITE", "Survey Invitation"),
                            ("REMINDER", "Survey Reminder"),
                            ("THANK_YOU", "Thank You Message"),
                            ("COMPLETION", "Survey Completion"),
                        ],
                        help_text="Purpose or context of the notification",
                        max_length=20,
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        blank=True,
                        help_text="Subject line for email or similar message types",
                        max_length=255,
                    ),
                ),
                (
                    "body",
                    models.TextField(help_text="Main content body of the notification"),
                ),
                (
                    "template",
                    models.TextField(
                        help_text="Optional raw or templated version of the message body"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Notification Template",
                "verbose_name_plural": "Notification Templates",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("token", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("opened_at", models.DateTimeField(blank=True, null=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                ("reminder_count", models.IntegerField(default=0)),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="surveys.survey",
                    ),
                ),
            ],
            options={
                "unique_together": {("survey", "email")},
            },
        ),
    ]
