# Generated by Django 5.2.3 on 2025-07-19 15:51

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BlueprintCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("icon", models.CharField(blank=True, max_length=50)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Blueprint Categories",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="QuestionBlueprint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "field_type",
                    models.CharField(
                        help_text="Field type code, e.g., 'TXT', 'MCQ'", max_length=3
                    ),
                ),
                ("category", models.CharField(max_length=50)),
                (
                    "blueprint_data",
                    models.JSONField(
                        default=dict, help_text="JSON structure of the question."
                    ),
                ),
                ("usage_count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["-usage_count", "title"],
            },
        ),
        migrations.CreateModel(
            name="SurveyBlueprint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "tags",
                    models.JSONField(
                        default=list, help_text="List of tags for filtering/search."
                    ),
                ),
                ("is_public", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("usage_count", models.PositiveIntegerField(default=0)),
                (
                    "blueprint_data",
                    models.JSONField(
                        help_text="JSON representation of the survey structure."
                    ),
                ),
                (
                    "preview_image",
                    models.ImageField(
                        blank=True,
                        help_text="Optional preview image for the blueprint.",
                        null=True,
                        upload_to="blueprint_previews/",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="survey_blueprints",
                        to="blueprints.blueprintcategory",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_survey_blueprints",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-usage_count", "-created_at"],
            },
        ),
    ]
