name: 'Setup System Dependencies'
description: 'Install system dependencies with caching'
inputs:
  packages:
    description: 'Space-separated list of packages'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Cache APT packages
      uses: actions/cache@v4
      with:
        path: /var/cache/apt
        key: apt-${{ runner.os }}-${{ hashFiles('**/package-list') }}
        restore-keys: |
          apt-${{ runner.os }}-

    - name: Install system dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y ${{ inputs.packages }}
