name: ActionLint

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  actionlint:
    name: Lint GitHub Workflows
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.2.1

    - name: Cache actionlint
      uses: actions/cache@v4
      with:
        path: ./actionlint
        key: actionlint-${{ runner.os }}

    - name: Download actionlint
      id: get_actionlint
      shell: bash
      run: |
        if [ ! -f ./actionlint ]; then
          bash <(curl -fsSL https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
        fi
        echo "executable=./actionlint" >> "$GITHUB_OUTPUT
