name: Deploy to Dev on PR Merge

# This workflow runs only when a pull request is merged into the 'develop' branch

on:
  pull_request:
    branches:
      - develop
    types:
      - closed

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy-to-testing:
    if: github.event.pull_request.merged == true
    name: Deploy to Testing Environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

  code-quality:
    if: github.event.pull_request.merged == true
    uses: ./.github/workflows/code-quality.yaml
    name: Code Quality Checks
    needs: deploy-to-testing
    secrets: inherit

  check-migrations:
    if: github.event.pull_request.merged == true
    uses: ./.github/workflows/migrations.yaml
    name: Migration Checks
    needs: code-quality
    secrets: inherit

  pra-backend-tests:
    if: github.event.pull_request.merged == true
    uses: ./.github/workflows/pra-backend-tests.yaml
    name: Backend Unit Tests
    with:
      full-crypto-flag: false
    needs: check-migrations
    secrets: inherit
