name: Check Migrations

on:
  workflow_call:

jobs:
  check-migrations:
    name: Django Migration Check
    runs-on:
      - self-hosted
      - oracle-linux-8
      - small

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.2.1  # Update version
      with:
        ref: ${{ github.event.pull_request.head.ref || github.sha }}

    - name: Add Poetry to PATH
      run: |
        if [ -d "/opt/poetry/bin" ]; then
          echo "/opt/poetry/bin" >> $GITHUB_PATH
        else
          echo "Poetry not found in expected location" >&2
          exit 1
        fi

    - name: Install system dependencies
      run: |
        sudo dnf install -y curl-devel openldap-devel libxml2-devel || {
          echo "Failed to install system dependencies" >&2
          exit 1
        }

    - name: Poetry install
      run: |
        poetry config virtualenvs.create false
        poetry install --with=dev --no-interaction

    - name: Verify Django install
      run: poetry run python -m django --version

    - name: Run makemigrations check
      working-directory: ./src
      env:
        DJANGO_SETTINGS_MODULE: settings.development
      run: |
        poetry run python manage.py makemigrations --check --dry-run --noinput
