name: Check Migrations

on:
  workflow_call:

jobs:
  check-migrations:
    name: Django Migration Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: false
          virtualenvs-in-project: false

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libldap2-dev libsasl2-dev libxml2-dev libxmlsec1-dev

      - name: Install dependencies with Poetry
        run: poetry install --with=dev --no-interaction

      - name: Verify Django install
        run: poetry run python -m django --version

      - name: Run makemigrations check
        working-directory: ./src
        env:
          DJANGO_SETTINGS_MODULE: settings.development
        run: |
          poetry run python manage.py makemigrations --check --dry-run --noinput
