name: PR Template Validation and Auto-Apply

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  validate-pr-template:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check PR Template Compliance
        id: template-check
        uses: actions/github-script@v7
        with:
          script: |
            const { data: pr } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });

            const prBody = pr.body || '';
            const prBodyNormalized = prBody.toLowerCase();

            const requiredSections = [
              'developer:',
              'summary of proposed changes',
              'type of change',
              'testing'
            ];

            const missingSections = requiredSections.filter(section =>
              !prBodyNormalized.includes(section)
            );

            if (missingSections.length > 0) {
              core.setFailed(`PR is missing required template sections: ${missingSections.join(', ')}`);

              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: `**PR Template Incomplete**\n\nThis pull request is missing the following required sections:\n${missingSections.map(s => `- ${s}`).join('\n')}\n\nPlease update your PR description to include all required sections from the template.`
              });
            } else {
              core.info('PR template compliance check passed');
            }
