name: PRA - Pre-Commit

on:
  workflow_call:

jobs:
  pra-precommit:
    name: Pre-commit Hooks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Disable Poetry virtualenv
        run: poetry config virtualenvs.create false

      - name: Install dependencies
        run: poetry install --no-interaction --only dev

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1
