name: 011 Pull Request Analysis

on:
  pull_request:

# Top-level concurrency controls the entire workflow file
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pull-request-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Analyze
        run: echo "Running analysis..."

  pre-commit-checks:
    uses: ./.github/workflows/pra-pre-commit.yml
    name: Pre-commit Hooks
    needs: pull-request-analysis
    secrets: inherit

  python-linting:
    uses: ./.github/workflows/python-linting-formatting.yml
    name: Python Linting
    needs: pull-request-analysis
    secrets: inherit

  codecov-validation:
    uses: ./.github/workflows/codecov-validation.yml
    name: Codecov Validation
    needs: consolidated-unit-tests
    secrets: inherit

  # check-migrations:
  #   uses: ./.github/workflows/migrations.yaml
  #   name: Check Migrations
  #   needs: pre-commit-checks
  #   secrets: inherit

  consolidated-unit-tests:
    uses: ./.github/workflows/pra-backend-tests.yaml
    name: Consolidated Unit Tests
    with:
      full-crypto-flag: false
    needs: pre-commit-checks
    secrets: inherit
