name: Pull Request Analysis

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - edited

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  setup:
    name: Setup Environment Variables
    runs-on: ubuntu-latest
    outputs:
      PYTHON_VERSION: ${{ vars.PYTHON_VERSION_DEV }}
      DEBUG: ${{ vars.DEBUG_DEV }}
      CONTAINER_INIT_SCRIPT: ${{ vars.CONTAINER_INIT_SCRIPT_DEV }}
    steps:
      - name: Confirm values from repository variables
        run: |
          echo "PYTHON_VERSION: ${{ vars.PYTHON_VERSION_DEV }}"
          echo "DEBUG: ${{ vars.DEBUG_DEV }}"

  actionlint:
    needs: setup
    name: Lint GitHub
    uses: ./.github/workflows/actionlint.yaml

  code-quality:
    needs: setup
    name: Code Quality Checks
    uses: ./.github/workflows/code-quality.yaml
    with:
      python-version: ${{ needs.setup.outputs.PYTHON_VERSION }}

  codecov-validation:
    name: Codecov Validation
    needs: setup
    uses: ./.github/workflows/codecov-validation.yaml

  check-migrations:
    needs: setup
    name: Check Migrations
    uses: ./.github/workflows/migrations.yaml
    with:
      python-version: ${{ needs.setup.outputs.PYTHON_VERSION }}
      debug: ${{ needs.setup.outputs.DEBUG }}
      container-init-script: ${{ needs.setup.outputs.CONTAINER_INIT_SCRIPT }}
      environment: "development"

  pra-backend-tests:
    needs: setup
    name: Backend Unit Tests
    uses: ./.github/workflows/pra-backend-tests.yaml
    with:
      python-version: ${{ needs.setup.outputs.PYTHON_VERSION }}
      debug: ${{ needs.setup.outputs.DEBUG }}
      container-init-script: ${{ needs.setup.outputs.CONTAINER_INIT_SCRIPT }}
      environment: "development"
    secrets: inherit
