name: Enforce Develop to Main PRs

on:
  pull_request:
    branches:
      - main

jobs:
  enforce-source-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Fail if PR is not from develop
        if: github.head_ref != 'develop'
        run: |
          echo "Only pull requests from 'develop' can be merged into 'main'."
          exit 1
